### ISSUE TITLE
Caffeine Breakdown Too Fast

### ISSUE THREAD

**Issue by kurtisnelson** [timdorr/dna#1]
If you look at line #788708, it should be switched to CC to increase the half-life of caffeine and require less cups of coffee for the same code output.

http://www.snpedia.com/index.php/Rs762551

**Comment by kurtisnelson** [comment]
Recomend cherry-picking https://github.com/bobthecow/kennethreitz-genome/commit/1cdf8abe01d61b4af521d3ecad36a05164babf8b

**Comment by timdorr** [comment]
#wontfix
